import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

function Logo() {
  return (
    <div className="inline-flex items-center justify-center mb-3" style={{ fontSize: '28px', fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1, color: '#1c1917' }}>
      <span>Timely</span>
      <svg style={{ width: '24px', height: '24px', color: '#047857', margin: '0 0.5px', position: 'relative', top: '-0.5px' }} viewBox="0 0 64 64" fill="none" stroke="currentColor">
        <circle cx="32" cy="32" r="28" strokeWidth="5.5" fill="none"/>
        <line x1="32" y1="32" x2="24" y2="17" strokeWidth="5.5" strokeLinecap="round"/>
        <line x1="32" y1="32" x2="44" y2="23" strokeWidth="4" strokeLinecap="round"/>
        <circle cx="32" cy="32" r="3" fill="currentColor" stroke="none"/>
      </svg>
      <span style={{ fontWeight: 500, color: '#047857' }}>ps</span>
    </div>
  )
}

export default function Terms() {
  const { t } = useTranslation()
  return (
    <div className="min-h-screen bg-stone-50 px-4 py-12">
      <div className="max-w-3xl mx-auto">

        {/* Header */}
        <div className="text-center mb-10">
          <Link to="/" className="inline-block mb-4">
            <Logo />
          </Link>
          <h1 className="text-3xl font-bold text-stone-900 mb-2">{t('terms.title')}</h1>
          <p className="text-sm text-stone-400">Last updated: March 26, 2026</p>
        </div>

        {/* Content card */}
        <div className="bg-white rounded-2xl shadow-sm border border-stone-200 p-8 md:p-12">

          <p className="text-stone-600 leading-relaxed mb-4">
            Welcome to TimelyOps. These Terms of Service ("Terms") govern your access to and use of the TimelyOps platform, website (timelyops.com), and related services (collectively, the "Service"). By creating an account or using the Service, you agree to be bound by these Terms.
          </p>
          <p className="text-stone-600 leading-relaxed mb-8">
            TimelyOps is operated by TimelyOps ("we," "us," or "our"), based in the Netherlands. If you do not agree to these Terms, do not use the Service.
          </p>

          {/* 1 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">1. Definitions</h2>
          <ul className="list-none text-stone-600 leading-relaxed mb-4 space-y-2">
            <li><strong>"Account"</strong> means the user account you create to access the Service.</li>
            <li><strong>"Organization"</strong> means the business entity (e.g., a housecleaning company) registered within the Service by an Account Owner.</li>
            <li><strong>"Account Owner"</strong> means the individual who creates an Organization and holds administrative rights over it.</li>
            <li><strong>"Authorized User"</strong> means any individual granted access to an Organization by the Account Owner, including managers and workers.</li>
            <li><strong>"Customer Data"</strong> means all data uploaded, entered, or generated by you or your Authorized Users through the Service, including client records, schedules, invoices, quotes, and payment records.</li>
            <li><strong>"Service"</strong> means the TimelyOps web application, APIs, AI-powered features, and all related features and functionality.</li>
            <li><strong>"End Client"</strong> means a customer of your business whose data you manage through the Service, or who interacts with the Service through public-facing features such as the AI booking agent, quote approval pages, or invoice viewing pages.</li>
          </ul>

          {/* 2 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">2. Eligibility and Account Registration</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            You must be at least 18 years old and capable of entering into a binding agreement to use the Service. By registering, you represent that you have the authority to bind your Organization to these Terms.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. You must notify us immediately at info@timelyops.com if you suspect unauthorized access.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We authenticate users via email one-time passcodes (OTP) and/or SMS verification. You are responsible for ensuring your contact information is accurate and current.
          </p>

          {/* 3 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">3. Use of the Service</h2>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">3.1 Permitted Use</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            The Service is provided for lawful business management purposes. You may use it to manage scheduling, clients, workers, quotes, invoices, payments, and related operations for your service business.
          </p>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">3.2 Prohibited Use</h3>
          <p className="text-stone-600 leading-relaxed mb-3">You agree not to:</p>
          <ul className="list-disc pl-6 text-stone-600 leading-relaxed mb-4 space-y-1">
            <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation</li>
            <li>Attempt to gain unauthorized access to the Service, other accounts, or our systems</li>
            <li>Reverse-engineer, decompile, or disassemble any part of the Service</li>
            <li>Interfere with or disrupt the integrity or performance of the Service</li>
            <li>Upload malicious code, viruses, or harmful content</li>
            <li>Share your account credentials with unauthorized third parties</li>
            <li>Use the AI booking agent or any automated features to send spam, unsolicited messages, or deceptive communications</li>
            <li>Attempt to circumvent rate limits, usage caps, or security measures</li>
            <li>Use the Service to store or process data that you do not have lawful authority to collect or use</li>
          </ul>

          {/* 4 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">4. Customer Data</h2>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">4.1 Ownership</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            You retain all rights to your Customer Data. We do not claim ownership of any data you or your Authorized Users enter into the Service.
          </p>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">4.2 License to Us</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            You grant us a limited, non-exclusive license to use, process, and store your Customer Data solely to provide and improve the Service. We will not sell, rent, or share your Customer Data with third parties except as described in our Privacy Policy or as required by law.
          </p>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">4.3 Data Accuracy</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            You are responsible for the accuracy and completeness of your Customer Data. We are not liable for any consequences arising from inaccurate or incomplete data entered into the Service, including incorrect pricing generated by the pricing matrix or AI booking agent based on data you have provided.
          </p>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">4.4 Data Portability</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            You may export your Customer Data at any time using the export features available in the Service. Upon termination of your account, we will make your data available for export for a period of 30 days, after which it may be permanently deleted.
          </p>

          {/* 5 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">5. Authorized Users and Staff Accounts</h2>
          <p className="text-stone-600 leading-relaxed mb-3">
            The Account Owner may create Authorized User accounts for managers and workers within their Organization. The Account Owner is responsible for:
          </p>
          <ul className="list-disc pl-6 text-stone-600 leading-relaxed mb-4 space-y-1">
            <li>All actions taken by Authorized Users within the Service</li>
            <li>Ensuring Authorized Users understand and comply with these Terms</li>
            <li>Promptly removing access for any Authorized User who leaves the Organization or no longer requires access</li>
            <li>Maintaining accurate contact information for all Authorized Users</li>
          </ul>
          <p className="text-stone-600 leading-relaxed mb-4">
            Authorized Users have varying levels of access based on their assigned role (owner, manager, or worker). The Account Owner is responsible for assigning appropriate roles and reviewing access levels regularly.
          </p>

          {/* 6 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">6. AI-Powered Features</h2>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">6.1 AI Booking Agent</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            The Service may include an AI-powered booking agent that interacts with your End Clients to collect information, provide pricing quotes, and schedule appointments on your behalf. The AI agent uses third-party artificial intelligence technology (currently provided by Anthropic) to generate responses.
          </p>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">6.2 AI Limitations and Disclaimers</h3>
          <p className="text-stone-600 leading-relaxed mb-3">You acknowledge and agree that:</p>
          <ul className="list-disc pl-6 text-stone-600 leading-relaxed mb-4 space-y-1">
            <li>AI-generated responses may contain errors, including incorrect pricing, scheduling conflicts, or inappropriate language</li>
            <li>The AI agent acts on your behalf and represents your business to End Clients — you are responsible for reviewing and confirming all bookings created by the agent</li>
            <li>No job or appointment created by the AI agent is confirmed without explicit approval from the Account Owner or an authorized manager</li>
            <li>We do not guarantee the accuracy, reliability, or appropriateness of AI-generated content</li>
            <li>You are responsible for reviewing the AI agent's interactions and promptly correcting any errors</li>
          </ul>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">6.3 AI Data Processing</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            Conversations between the AI agent and your End Clients are processed by third-party AI providers (currently Anthropic) and stored in the Service. By enabling AI features, you consent to this processing on behalf of your Organization. You are responsible for informing your End Clients that they may be interacting with an AI-powered system.
          </p>

          <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">6.4 AI Fair Use</h3>
          <p className="text-stone-600 leading-relaxed mb-4">
            AI-powered features are subject to fair use limits. We reserve the right to throttle, suspend, or modify AI features for any Organization that generates excessive or abusive usage, including but not limited to automated scripts, bot traffic, or attempts to circumvent rate limits.
          </p>

          {/* 7 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">7. Communications Sent on Your Behalf</h2>
          <p className="text-stone-600 leading-relaxed mb-3">
            The Service sends emails and SMS messages to your End Clients on your behalf, including but not limited to: quote notifications, invoice delivery, payment receipts, booking confirmations, and appointment reminders.
          </p>
          <p className="text-stone-600 leading-relaxed mb-3">You acknowledge and agree that:</p>
          <ul className="list-disc pl-6 text-stone-600 leading-relaxed mb-4 space-y-1">
            <li>You are the sender of these communications, and TimelyOps acts as your service provider in transmitting them</li>
            <li>You are responsible for having appropriate consent from your End Clients to receive these communications</li>
            <li>You will comply with all applicable laws regarding electronic communications, including CAN-SPAM (US), GDPR (EU), and any applicable local regulations</li>
            <li>We reserve the right to suspend communication features for any Organization that generates spam complaints or violates applicable communication laws</li>
          </ul>

          {/* 8 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">8. Pricing and Payment</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            TimelyOps offers subscription-based pricing. Current pricing tiers and features are displayed on our website or within the Service.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We reserve the right to change our pricing with 30 days' notice. Price changes will take effect at the start of your next billing cycle after the notice period.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Subscription fees are billed in advance on a monthly or annual basis, depending on the plan you select. Subscriptions auto-renew at the end of each billing period unless cancelled before the renewal date. All fees are non-refundable except where required by applicable law.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            A one-time implementation fee may apply for new customer onboarding, as specified at the time of sign-up.
          </p>

          {/* 9 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">9. Fair Use and Usage Limits</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            Each subscription tier includes defined limits for staff accounts, features, and usage. The specific limits for your tier are described on our pricing page and within the Service.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We reserve the right to impose additional limits on API calls, AI agent conversations, SMS messages, email sends, data storage, and other resource-intensive features to ensure fair use across all customers. If your usage significantly exceeds normal patterns, we will notify you and work with you to find an appropriate solution, which may include upgrading to a higher tier.
          </p>

          {/* 10 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">10. Free Trials, Founding Customers, and Beta Features</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            We may offer free trials, founding customer discounts, or beta features from time to time. These are provided "as is" and may be modified or discontinued with 30 days' notice.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Free trials automatically convert to paid subscriptions unless cancelled before the trial period ends. Founding customer pricing is subject to the terms agreed at the time of enrollment and may be time-limited.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Beta features are provided without warranty and may be unstable, incomplete, or removed without notice. Your use of beta features is at your own risk.
          </p>

          {/* 11 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">11. Service Availability</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            We strive to maintain high availability but do not guarantee uninterrupted access to the Service. The Service is provided without any uptime guarantee or service level agreement (SLA).
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We may suspend access for maintenance, updates, or circumstances beyond our control. We will make reasonable efforts to provide advance notice of planned maintenance.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We are not liable for any loss or damage resulting from service interruptions, including missed bookings, delayed communications, or data unavailability.
          </p>

          {/* 12 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">12. Third-Party Services</h2>
          <p className="text-stone-600 leading-relaxed mb-3">
            The Service integrates with third-party services including but not limited to:
          </p>
          <ul className="list-disc pl-6 text-stone-600 leading-relaxed mb-4 space-y-1">
            <li>Supabase (database hosting and authentication)</li>
            <li>Vercel (web hosting)</li>
            <li>Twilio (SMS delivery and phone services)</li>
            <li>Resend (email delivery)</li>
            <li>Anthropic (AI language model for booking agent and AI features)</li>
          </ul>
          <p className="text-stone-600 leading-relaxed mb-4">
            Your use of these third-party services is subject to their respective terms and policies. We are not responsible for the availability, accuracy, or practices of any third-party service.
          </p>

          {/* 13 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">13. Intellectual Property</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            The Service, including its design, code, features, documentation, and branding (including the TimelyOps name and Clock-O logo), is owned by TimelyOps and protected by applicable intellectual property laws.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            These Terms do not grant you any right to use our trademarks, logos, or branding without our prior written consent.
          </p>

          {/* 14 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">14. Limitation of Liability</h2>
          <div className="bg-stone-50 border border-stone-200 rounded-xl p-4 mb-4">
            <p className="text-stone-700 leading-relaxed mb-3 text-sm font-medium uppercase tracking-wide">
              To the maximum extent permitted by law, TimelyOps shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising from your use of or inability to use the Service.
            </p>
            <p className="text-stone-700 leading-relaxed text-sm font-medium uppercase tracking-wide">
              Without limiting the foregoing, TimelyOps shall not be liable for any damages arising from: (a) errors or inaccuracies in AI-generated content, including incorrect pricing quotes or scheduling suggestions; (b) communications sent to your End Clients through the Service; (c) actions taken by your Authorized Users; or (d) third-party service outages or failures.
            </p>
          </div>
          <p className="text-stone-600 leading-relaxed mb-4">
            Our total aggregate liability for any claims arising from or related to these Terms or the Service shall not exceed the amount you paid us in the twelve (12) months preceding the claim.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law, including liability for fraud or willful misconduct.
          </p>

          {/* 15 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">15. Indemnification</h2>
          <p className="text-stone-600 leading-relaxed mb-3">
            You agree to indemnify and hold harmless TimelyOps and its officers, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising from:
          </p>
          <ul className="list-disc pl-6 text-stone-600 leading-relaxed mb-4 space-y-1">
            <li>Your use of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your violation of any third-party rights</li>
            <li>Communications sent to your End Clients through the Service</li>
            <li>The actions of your Authorized Users</li>
            <li>Claims by your End Clients arising from AI agent interactions, pricing quotes, or booking errors</li>
            <li>Your failure to comply with applicable data protection or communication laws</li>
          </ul>

          {/* 16 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">16. Termination</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            You may terminate your account at any time by contacting us at info@timelyops.com. Termination takes effect at the end of your current billing period.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We may suspend or terminate your access if you violate these Terms, fail to pay fees when due, engage in abusive usage of AI or communication features, or if we reasonably believe your use poses a risk to the Service or other users. We will provide notice where practicable.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Upon termination, your right to use the Service ceases immediately. Your Customer Data will be available for export for 30 days following termination, after which it may be permanently deleted.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Sections 4 (Customer Data), 6.2 (AI Disclaimers), 14 (Limitation of Liability), 15 (Indemnification), and 19 (Governing Law) survive termination.
          </p>

          {/* 17 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">17. Data Processing Agreement</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            If your use of the Service involves the processing of personal data subject to the GDPR or similar data protection regulations, and you require a Data Processing Agreement (DPA), please contact us at{' '}
            <a href="mailto:info@timelyops.com" className="text-emerald-700 hover:underline">info@timelyops.com</a>.
          </p>

          {/* 18 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">18. Changes to These Terms</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            We may update these Terms from time to time. We will notify you of material changes by email or through the Service at least 30 days before they take effect.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Your continued use of the Service after changes take effect constitutes acceptance of the updated Terms. If you do not agree with the changes, you may terminate your account.
          </p>

          {/* 19 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">19. Governing Law and Dispute Resolution</h2>
          <p className="text-stone-600 leading-relaxed mb-4">
            These Terms are governed by the laws of the Netherlands. Any disputes arising from these Terms or the Service shall be submitted to the exclusive jurisdiction of the competent courts in Amsterdam, the Netherlands.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            For users within the European Union, nothing in these Terms affects your rights under mandatory consumer protection laws of your country of residence.
          </p>

          {/* 20 */}
          <h2 className="text-xl font-bold text-stone-900 mt-8 mb-3">20. Contact Information</h2>
          <p className="text-stone-600 leading-relaxed mb-3">If you have questions about these Terms, please contact us:</p>
          <ul className="list-none text-stone-600 leading-relaxed mb-4 space-y-1">
            <li><strong>Email:</strong> <a href="mailto:info@timelyops.com" className="text-emerald-700 hover:underline">info@timelyops.com</a></li>
            <li><strong>Website:</strong> <a href="https://timelyops.com" className="text-emerald-700 hover:underline">timelyops.com</a></li>
            <li><strong>Location:</strong> The Netherlands</li>
          </ul>

          {/* Cross-link */}
          <div className="mt-10 pt-6 border-t border-stone-100 text-sm text-stone-400">
            See also:{' '}
            <Link to="/privacy" className="text-emerald-700 hover:underline">Privacy Policy</Link>
          </div>
        </div>

        <p className="text-center mt-6 text-xs text-stone-400">
          <Link to="/login" className="hover:text-stone-600">Sign in to TimelyOps</Link>
        </p>
      </div>
    </div>
  )
}
